trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - operator/*
      - azure-pipelines.yml
      - requirements.txt
      - Dockerfile

pr: none

pool:
  vmImage: 'cg-ubuntu-2004'

variables:
  IMAGE_NAME: chelnak/app-insights-operator

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: Use GitVersion
    inputs:
      useConfigFile: true
      configFilePath: 'GitVersion.yml'

  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: Docker Hub

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: Dockerfile
      repository: $(IMAGE_NAME)
      tags: |
        $(build.buildnumber)
        latest

  - task: Docker@2
    displayName: Push Image
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      repository: $(IMAGE_NAME)
      tags: $(build.buildnumber)

  - task: Docker@2
    displayName: Push latest tag if master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      repository: $(IMAGE_NAME)
      tags: latest
